[build-system]
requires = [
    "param >=1.9.2",
    "pyct >=0.4.4",
    "setuptools >=42",
    "bokeh >=3.1.1,<3.3.0",
    "pyviz_comms >=0.7.4",
    "requests",
    "bleach",
    "packaging",
    "tqdm >=4.48.0",
    "wheel"
]

[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    ".tox",
    ".eggs",
    "*.egg",
    "doc",
    "dist",
    "build",
    "_build",
    "examples",
    ".ipynb_checkpoints",
    "node_modules",
    "apps",
]
ignore = [
    "E402",
    "E712",
    "E731",
    "E741",
    "W605",
    "E701", # Multiple statements on one line
]
line-length = 165
select = [
    "E",
    "F",
    "W",
]

[tool.ruff.per-file-ignores]
"panel/tests/ui/jupyter_server_test_config.py" = ["F821"]

[tool.codespell]
ignore-words-list = "nd,doubleclick"
skip = "doc/generate_modules.py,examples/reference/templates/FastGridTemplate.ipynb,panel/eslint.js,panel/package-lock.json,panel/package.json"
write-changes = true
